# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20171111_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
