# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_singer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Details',
        ),
    ]
