# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20171111_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
