# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20171111_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Slug_Field',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
