# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_slug_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Slug_Field',
            new_name='slug_field',
        ),
    ]
