# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_song_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Votes',
        ),
    ]
