# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_remove_song_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
