# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_song_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ImageUrl',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
