# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import songs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_song_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='ImageUrl',
        ),
        migrations.AlterField(
            model_name='song',
            name='Genre',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[songs.validators.validate_Genre]),
        ),
    ]
