# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_auto_20171116_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
