# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_auto_20171116_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.AlterField(
            model_name='song',
            name='Genre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
